import numpy as np
import json
import os

input_folder = "../../../outputs/before/"
output_path = "../../../../src/tensor1.py"

def compute_signature_tensor(A):
    A = np.asarray(A, dtype=np.uint8)
    n_qubits, n_terms = A.shape
    print(f"Computing signature tensor for {n_qubits} qubits and {n_terms} terms...")
    S = np.zeros((n_qubits, n_qubits, n_qubits), dtype=np.uint8)

    for j in range(n_terms):
        col = A[:, j]
        for alpha in range(n_qubits):
            for beta in range(n_qubits):
                for gamma in range(n_qubits):
                    S[alpha, beta, gamma] ^= (col[alpha] & col[beta] & col[gamma])

    return S


def export_all_signature_tensors(folder_path, output_path):
    with open(output_path, "w") as f:
        # Header and imports
        f.write('"""Autogenerated signature tensors."""\n\n')
        f.write("import numpy as np\n\n\n")

        print(os.listdir(folder_path))
        for filename in sorted(os.listdir(folder_path)):
            if filename.endswith(".txt") or filename.endswith(".json"):
                filepath = os.path.join(folder_path, filename)
                print(f"Processing: {filename}")
                try:
                    with open(filepath, 'r') as infile:
                        table = json.load(infile)
                    table = np.array(table).T
                    S = compute_signature_tensor(table)

                    var_name = os.path.splitext(filename)[0]
                    var_name = var_name.replace("-", "_").replace(" ", "_")
                    var_name = f"_SIG_{var_name.upper()}"

                    # Write tensor
                    f.write(f"{var_name} = np.array(\n")
                    f.write("    [\n")
                    for matrix in S:
                        f.write("        [\n")
                        for row in matrix:
                            row_str = ", ".join(str(int(x)) for x in row)
                            f.write(f"            [{row_str}],\n")
                        f.write("        ],\n")
                    f.write("    ],\n")
                    f.write("    dtype=np.int32,\n")
                    f.write(")\n\n")
                except Exception as e:
                    print(f"Failed to process {filename}: {e}")

# Run the export
export_all_signature_tensors(input_folder, output_path)
print(f"Done. All tensors written to {output_path}")
